name: "Middle - Foundation"
division: middle
playersPerTeam: 3
penalties:
  noPenalty:
    duration:
      secs: 0
      nanos: 0
    incremental: false
  illegalPositioning:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  motionInSet:
    duration:
      secs: 10
      nanos: 0
    incremental: false
  localGameStuck:
    duration:
      secs: 30
      nanos: 0
    incremental: false
  incapableRobot:
    duration:
      secs: 30
      nanos: 0
    incremental: false
  pickedUp:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  ballHolding:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  leavingTheField:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  playingWithArmsHands:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  pushing:
    duration:
      secs: 30
      nanos: 0
    incremental: true
  sentOff:
    duration:
      secs: 0
      nanos: 0
    incremental: false
  substitute:
    duration:
      secs: 0
      nanos: 0
    incremental: false
penaltyDurationIncrement:
  secs: 15
  nanos: 0
setPlays:
  noSetPlay:
    duration:
      secs: 0
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
  kickOff:
    duration:
      secs: 10
      nanos: 0
    readyDuration:
      secs: 45
      nanos: 0
  directFreeKick:
    duration:
      secs: 45
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
  indirectFreeKick:
    duration:
      secs: 45
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
  penaltyKick:
    duration:
      secs: 60
      nanos: 0
    readyDuration:
      secs: 45
      nanos: 0
  throwIn:
    duration:
      secs: 45
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
  goalKick:
    duration:
      secs: 45
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
  cornerKick:
    duration:
      secs: 45
      nanos: 0
    readyDuration:
      secs: 0
      nanos: 0
halfDuration:
  secs: 600
  nanos: 0
halfTimeBreakDuration:
  secs: 600
  nanos: 0
extraHalfDuration:
  secs: 300
  nanos: 0
timeoutDuration:
  secs: 300
  nanos: 0
timeoutsPerTeam: 1
refereeTimeoutDuration:
  secs: 600
  nanos: 0
messagesPerTeam: 12000
messagesPerTeamPerExtraMinute: 600
mercyRuleScoreDifference: 10
penaltyShots: 3
suddenDeathPenaltyShots: 3
penaltyShotDuration:
  secs: 60
  nanos: 0
delayAfterPlaying:
  secs: 10
  nanos: 0
