camera:
  color_topic: /camera/camera/color/image_raw
  depth_topic: /camera/camera/aligned_depth_to_color/image_raw
  intrin_topic: /camera/camera/color/camera_info
  intrin:
    fx: 647.207275
    fy: 646.288025
    cx: 650.817383
    cy: 367.851227
    distortion_model: 0
    distortion_coeffs:
      []
  extrin:
    -
      - 0.000261429086
      - -0.00720987096
      - 0.999973953
      - -0.00187119353
    -
      - -0.99998641
      - 0.00521431491
      - 0.000299027888
      - -0.0300600827
    -
      - -0.00521633541
      - -0.999960423
      - -0.00720840972
      - -0.0137843648
    -
      - 0
      - 0
      - 0
      - 1
  pitch_compensation: 0
  yaw_compensation: 0
  z_compensation: 0
detection_model:
  model_path: /home/booster/Workspace/robocup_demo/src/vision/model/best_orin_10.3.engine
  confidence_threshold: 0.2
  nms_threshold: 0.4
  classnames: [Ball, Goalpost, Person, LCross, TCross, XCross, PenaltyPoint, Opponent, BRMarker]
  post_process:
    single_ball_assumption: false
    confidence_thresholds:
      Ball: 0.2
      Goalpost: 0.2
      Person: 0.2
      LCross: 0.5
      TCross: 0.1
      XCross: 0.1
      PenaltyPoint: 0.1
      Opponent: 0.5
      BRMarker: 0.2
segmentation_model:
  model_path: /home/booster/Workspace/robocup_demo/src/vision/model/best_seg_orin_10.3.engine
  confidence_threshold: 0.3
  nms_threshold: 0.9
use_depth: true
ball_pose_estimator:
  use_depth: true
  radius: 0.109
  down_sample_leaf_size: 0.01
  cluster_distance_threshold: 0.01
  fitting_distance_threshold: 0.01
  minimum_cluster_size: 150
  filter_distance: 1.2
  check_ball_height: true
human_like_pose_estimator:
  use_depth: true
  down_sample_leaf_size: 0.01
  fitting_distance_threshold: 0.01
  statistic_outlier_multiplier: 0.01
field_marker_pose_estimator:
  refine: false
  line_segment_area_threshold: 75
calibration:
  sync_max_time_diff_ms: 5000
  offset:
    exclude_distance: 2.0
    zero_translation: true
    field_marker_path: /home/booster/Workspace/Robocup-Humanoid-/src/vision/config/field.yaml
  handeye:
    calibration_time: 2026-04-21-15-14-27
    reprojection_error: 3.5257067920115368
misc:
  save_data_nonstationary: true
robot_name: ""
show_det: 1
